### ISSUE TITLE
V1.0

### ISSUE THREAD

**Issue by phthhieu** [Thinkei/hero-jira-chrome-extension#1]
# Road to V1.0

## Features
- [x] @phthhieu Allow to sync card status
- [x] @christhuong Allow creating Jira card from github Pull
- [x] @christhuong Allow injecting Jira key to github pull title after creating a Jira card.
- [x] @christhuong Allow to create Jira card from github Issue
- [x] @christhuong Show notification if the card is not updated in a pull, eg card is in to-do but opened PR.
- [x] @christhuong Select existing card as card of the github pull/issue
- [x] @christhuong  Config github token

 
## Setup
- [x] @phthhieu Store jira configuration: host/token/email with React.Context, remove passing from the hierararchy. (or using any state management library: overmind / redux / mobx)
- [x] @phthhieu Prettier code
- [x] @phthhieu Fix hero icons are not loaded on prod build
- [x] @phthhieu Publish to chrome store https://chrome.google.com/webstore/detail/hero-jira/pdpegfiiiddlbdjajfefieoillffngjh
- [x] @phthhieu Separate development & prod app, so we can install both versions
- [x] @phthhieu Setup circleci to auto publish the extension to Chrome web store https://circleci.com/blog/continuously-deploy-a-chrome-extension/

**Comment by hanh090** [comment]
I want to have 2 new features:
- Create git branch from Jira
- Create PR template with that jira card

**Comment by hanh090** [comment]
- Show "Approve" UI to "run full test" for main app

**Comment by phthhieu** [comment]
@hanh090 

> Show "Approve" UI to "run full test" for main app

=> It is not my intention to sync with CircleCI, feel free to open PR or commit, it will be a useful feature.

> Create git branch from Jira

Unclear.

> Create PR template with that jira card

Unclear.

Could you elaborate?

**Comment by hanh090** [comment]
> Create git branch from Jira

I want a function like what a Minh do for emacs but smarter :D, it will suggest a branch name from Jira card, from that I can copied and paste when create new branch

> Create PR template with that jira card

when create a PR, I must switch back and forth to pick up the jira card and link, so it would be helpful if we can inject that information automatically when create a PR

**Comment by phthhieu** [comment]
@hanh090 Ok, let me organise that idea. Btw for circleci, if you think it is worth to have, feel free to commit or open a PR.
